apiVersion: v1
kind: Pod
metadata:
  name: simple-stateful
  labels:
    app: simple-stateful
spec:
  containers:
  - name: simple-stateful
    image: minninnewah/simple_stateful:latest
    ports:
    - containerPort: 8080
      protocol: TCP
  nodeSelector:
    kubernetes.io/hostname: worker-1
---
apiVersion: v1
kind: Service
metadata:
  name: simple-stateful
spec:
  type: NodePort
  selector:
    app: simple-stateful
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 8080
      nodePort: 30003