apiVersion: apps/v1
kind: Deployment
metadata:
    name: react-backbone
    labels:
        app: react-backbone
spec:
    replicas: 1
    selector:
        matchLabels:
            app: react-backbone
    template:
        metadata:
            labels:
                app: react-backbone
        spec:
            containers:
              - name: react-backbone
                image: minninnewah/react_backbone:latest
                imagePullPolicy: Always
                args:
---
apiVersion: v1
kind: Service
metadata:
  name: react-backbone
spec:
  type: NodePort
  selector:
    app: react-backbone
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 8080
      nodePort: 30002