apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
data:
  user: YWRtaW4=
  password: YWRtaW4=
  database: YWRtaW4=
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-edge
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
  volumeName: postgres-pv-edge
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-edge
  labels:
    type: local
spec:
  capacity:
    storage: 500Mi
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgres-pv-local
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-db
spec:
  replicas: 1
  selector:
    matchLabels:
      name: edge-db
  template:
    metadata:
      labels:
        name: edge-db
        tier: backend
    spec:
      containers:
        - name: edge-db
          image: mdillon/postgis:10
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: user

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password

            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: database

          volumeMounts:
            - name: postgres-volume-mount
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-volume-mount
          persistentVolumeClaim:
            claimName: postgres-pvc-edge
---
apiVersion: v1
kind: Service
metadata:
  name: edge-db
spec:
  selector:
    name: edge-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
