apiVersion: apps/v1
kind: Deployment
metadata:
    name: challenge-handler
    labels:
        app: challenge-handler
spec:
    replicas: 1
    selector:
        matchLabels:
            app: challenge-handler
    template:
        metadata:
            labels:
                app: challenge-handler
        spec:
            containers:
              - name: challenge-handler
                image: minninnewah/challenge_handler:latest
                imagePullPolicy: Always
                args:
---
apiVersion: v1
kind: Service
metadata:
  name: challenge-handler
spec:
  selector:
    app: challenge-handler
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 8080