# https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-2-pv
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/nginx-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-2-pv
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/nginx-2-pv
---
apiVersion: v1
kind: Service
metadata:
  #labels:
  #  app: nginx
  name: nginx2
spec:
  #clusterIP: None
  type: NodePort
  ports:
    - name: web
      protocol: TCP
      port: 5005
      targetPort: 80
      nodePort: 30005
  selector:
    app: nginx2
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: simple-stateful-set_2
spec:
  replicas: 1  # the default is 1
  selector:
    matchLabels:
      app: nginx2  # has to match .spec.template.metadata.labels
  #serviceName: "nginx"
  template:
    metadata:
      labels:
        app: nginx2  # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - image: nginx
          name: nginx2
          ports:
            - containerPort: 80
              name: web
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: www
  volumeClaimTemplates:
    - metadata:
        name: www
      spec:
        accessModes: ["ReadWriteMany"]
        resources:
          requests:
            storage: 1Gi
        storageClassName: standard