apiVersion: apps/v1
kind: Deployment
metadata:
    name: drone
    labels:
        app: drone
spec:
    replicas: 1
    selector:
        matchLabels:
            app: drone
    template:
        metadata:
            labels:
                app: drone
        spec:
            containers:
              - name: drone
                image: minninnewah/drone:latest
                imagePullPolicy: Always
                args:
---
apiVersion: v1
kind: Service
metadata:
  name: drone
spec:
  selector:
    app: drone
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 8080