apiVersion: apps/v1
kind: Deployment
metadata:
    name: drone-distribution
    labels:
        app: drone-distribution
spec:
    replicas: 1
    selector:
        matchLabels:
            app: drone-distribution
    template:
        metadata:
            labels:
                app: drone-distribution
        spec:
            containers:
              - name: drone-distribution
                image: minninnewah/drone_distribution:latest
                imagePullPolicy: Always
                args:
---
apiVersion: v1
kind: Service
metadata:
  name: drone-distribution
spec:
  selector:
    app: drone-distribution
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 8080