apiVersion: apps/v1
kind: Deployment
metadata:
    name: drones-management
    labels:
        app: drones-management
spec:
    replicas: 1
    selector:
        matchLabels:
            app: drones-management
    template:
        metadata:
            labels:
                app: drones-management
        spec:
            containers:
              - name: drones-management
                image: minninnewah/drones_management:latest
                imagePullPolicy: Always
                args:
---
apiVersion: v1
kind: Service
metadata:
  name: drones-management
spec:
  selector:
    app: drones-management
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 8080